### ISSUE TITLE
Variable databases

### ISSUE THREAD

**Issue by julevdl** [amosproj/amos-ss2021-project2-context-map#10]
## User story
1. As a systemadmin of the running application
2. I want / need to use different datasets
3. So that I can use the tool independently of the data source

## Acceptance criteria
* Usable with RDF
* Usable with neo4j
* Usable with CPU 24/7 's exemplary data set

## Definition of done
* Added only after week 5
* The same for all features

**Comment by zuberman35** [comment]
closed as requirements changed
