### ISSUE TITLE
Error component

### ISSUE THREAD

**Issue by CatoLeanTruetschel** [amosproj/amos-ss2021-project2-context-map#109]
Build a React component that renders a javascript `Error` object into HTML. The view shall display a pictogram that is ~25% of the width of the parent container. Below the pictogram is the error message displayed.  
The following types of errors are handled with special pictograms:
* NotFound
* NetworkError
* CancellationError

**Comment by IgorShmelev** [comment]
Because I just saw it in the Material UI doc: Maybe this could be realized via a [snackbar](https://material-ui.com/de/components/snackbars/) element?

**Comment by CatoLeanTruetschel** [comment]
Maybe it's not quite clear from the description above. What we plan to implement is a complete page, that is rendered instead the actual page. Reporting error via notifications is a complete separate issue.
