### ISSUE TITLE
Deep Dive Information Visualisation

### ISSUE THREAD

**Issue by julevdl** [amosproj/amos-ss2021-project2-context-map#11]
## User story
1. As an engineer & portfolio manager
2. I want / need to apply different forms of visualization to my query results
3. So that different needs can be displayed in different ways

## Acceptance criteria
* No implementation (yet) but research, discussion and specification
* Overview over various visualization types

## Definition of done
* Added only after week 5
* The same for all features

**Comment by CatoLeanTruetschel** [comment]
Implemented via 98fe3bd6b172bb95a94059f70b55fb30c5d12589
