### ISSUE TITLE
Bigger test set

### ISSUE THREAD

**Issue by joluj** [amosproj/amos-ss2021-project2-context-map#117]
We need a bigger test set. We currently have 4 nodes (of 2 typed) and 3 edges (of 2 types).
The bigger test set should contain more different nodes/edges, especially with more property-types, e.g. properties with types Date, List of Strings, List of numbers, ... 
With the current test set it's also not possible to create a 100% branch coverage since we only have the property types string and number.

**Comment by PianoRollRepresentation** [comment]
I created a bigger test set. The problem now is that most of the e2e-tests are fitted to the smaller test sets and fail for the bigger one. Maybe it is a good idea that it would be possible to choose the testing-dump in the e2e-test. That would be possible by manipulating the neo4jService-config database-name. But I have no idea how to change the name of a neo4j-database. Currently all dbms have the name 'neo4j'

**Comment by joluj** [comment]
Since we run every test in one run, the test itself must decide on the database name. However, this will not happen since this would mean that the test must restart the backend server with different env variables.
Better is starting multiple backends on different ports where each instance connects to a different db. Each test might then redirect the original requests to other ports (e.g. redirect `http://localhost:8080/api/search/all` to `http://localhost:8081/api/search/all`). This is simple, but requires a change in the CI.
Let's discuss that on the dev meeting on monday.
