### ISSUE TITLE
Sliderfunction for nodes & edges

### ISSUE THREAD

**Issue by julevdl** [amosproj/amos-ss2021-project2-context-map#134]
## User story
1. As a process manager
2. I want / need to regulate the number of nodes shown in the visualization
3. So that I can adjust the graphics to my personal queries

## Acceptance criteria
* Displayed as slider 
* Label: number of nodes/edges (respectively)
* Label Left: 0 (Min)
* Label Right: 1000 (Max) (-> changes if number of nodes/edges in dataset is smaller)
* Possible visualization:
*![Bildschirmfoto 2021-05-26 um 09 01 32](https://user-images.githubusercontent.com/73954483/119616506-fa16ae80-be00-11eb-94ec-fa34f941da1e.png)

## Definition of done
* Documentation conform with tsdoc
* Reviewed with 4 eyes principle
* Understandable documentation for developers

**Comment by joluj** [comment]
Blocked by #47
