### ISSUE TITLE
Filtermenu Separate: Nodes & Relationships

### ISSUE THREAD

**Issue by julevdl** [amosproj/amos-ss2021-project2-context-map#135]
## User story
1. As a business manager
2. I want / need have a clear distinction of nodes & relationships while filtering
3. So that I can more easily find what I am looking for

## Acceptance criteria
* Visualization option: 
* 
![Bildschirmfoto 2021-05-19 um 08 27 57](https://user-images.githubusercontent.com/73954483/118765989-2029d500-b87c-11eb-9845-f35f23b72576.png)
* Each filter applicable for nodes will be displayed on nodes page 
* Each filter applicable for relationship will be displayed on relationship page

## Definition of done
* Documentation conform with tsdoc
* Reviewed with 4 eyes principle
* Understandable documentation for developers

**Comment by CatoLeanTruetschel** [comment]
Nodes and edges were already separated in the initial implementation of #47
