### ISSUE TITLE
Software Architecture

### ISSUE THREAD

**Issue by julevdl** [amosproj/amos-ss2021-project2-context-map#14]
**Verlinkung - Interaktion mit Issue "Choose and set up database"** 
Prepare a description of the planned software architecture; include
An overview diagram of runtime components (one page)
An overview diagram of code components (one page)
A summary of the underlying technology stack (one page)
A textual explanation of the diagrams and choices (one page)
Create a PDF and upload the file before class to the Deliverables folder.

**Comment by zuberman35** [comment]
To get a holistic view on the architecture, maybe have a look at the Service Blueprint :)
/[https://www.nngroup.com/articles/service-blueprints-definition/](url)

**Comment by CatoLeanTruetschel** [comment]
The SW architecture is done and committed. I proopse to close this and open a follow up, if we need to modify and/or extend the architecture.
/CC @joluj @IgorShmelev

**Comment by julevdl** [comment]
Agreed, issue can be closed. The Software Architecture doc can be found in the respective "Deliverables" folder on github or in our Shared Google Drive Folder.
