### ISSUE TITLE
Create NodeType and EdgeType Components

### ISSUE THREAD

**Issue by joluj** [amosproj/amos-ss2021-project2-context-map#140]
We need reusable Node- and Edge-HTML-Components so that the representation of them is equal in all parts of the app. (Example #30 and #47)

**Comment by CatoLeanTruetschel** [comment]
Why do you assume that an entry in the filter menu should look the same as in the search results?

**Comment by joluj** [comment]
It's just a nice visual thing. I don't like it if the PERSON node in the search results is green and oval and in the filter methods it's red and a rectangle.
After that issue, the same things will look the same in the whole app.

**Comment by joluj** [comment]
Maybe a better name would be "Create Node*Types* and Edge*Types* Components". This is exactly what I need as components in the search anyway, so I can also implement it in a reusable way.
I have mentioned the filter since you can select Edge-/Node-Types. There you could use these components as well.

I think it's simpler than #99 since this issue just says that we create reusable components, specific styling is not needed yet for this issue. #99 is then the improvement.

**Comment by CatoLeanTruetschel** [comment]
If you need to implement it for the search anyway, I propose that you implement them in the way you need them (maybe already build them as dedicated components) and if that's ready we can refactor the code-base of the filter until we are able to switch to these new components. That then is however a separate step that cleans up the code base.
