### ISSUE TITLE
Searchfunction mapping

### ISSUE THREAD

**Issue by zuberman35** [amosproj/amos-ss2021-project2-context-map#234]
## User story
1. As a  business user
2. I want / need to find nodes/edges in the dataset through the search bar and have them shown to me in the visualization
3. So that I do not need to look for them visually in the current visualization

## Acceptance criteria
* Searchbar implemented for each visualization (top right corner)
* When clicking on desired result, highlight in current visualization:

1. Homepage -> Graph
2. Dashboard -> Graph
3. Exploration -> Graph
4. Data -> Data (only leads to page for now)
5. Graph -> Graph
6. Schema -> Schema (only leads to page for now)
7. Hierarchies -> Hierarchies

* entity types highlights all entities belonging to this type
* when not in filtered graph, show warning 

## Definition of done
* Documentation conform with tsdoc
* Reviewed with 4 eyes principle
* Did not break other code
* Understandable documentation for developers

**Comment by joluj** [comment]
- When on other pages -> redirect to the pages (see above)
- Don't remember the search selection when pages are changed
