### ISSUE TITLE
Visualization Chord Diagram

### ISSUE THREAD

**Issue by julevdl** [amosproj/amos-ss2021-project2-context-map#308]
## User story
1. As a IT project manager
2. I want / need to see a summary of connections between nodes
3. So that I can see the importance of the flow

## Acceptance criteria
* Displayed on subpage in main menu visualization 
* Added as clickable option in dashboard #45 
* In Exploration Logic #289 Assign the weight "P" to this diagram and change the preview title to "Chord diagram" instead of "Pie Chart"
* In circle only display nodes -> relations are displayed as chords 
* Chords are number of edges -> modify thickness of chords relative to number of edges 
* "Focus function": mouseover allows to focus on node -> everything else fades 
* Stays consistent with prev. used color scheme
* Visualization example:  

![image](https://user-images.githubusercontent.com/65014902/122177516-fddca480-ce85-11eb-8e68-d40aa960509f.png)
![image](https://user-images.githubusercontent.com/65014902/122177593-0df48400-ce86-11eb-9463-20c1b8e92eff.png)

## Definition of done
* Documentation conform with tsdoc
* Reviewed with 4 eyes principle
* Did not break other code
* Understandable documentation for developers

**Comment by derwehr** [comment]
Regarding feasibility: There's a [react component](https://www.npmjs.com/package/react-chord-diagram) for building [d3 chord-diagrams](https://github.com/d3/d3-chord). 
Also, [here's a tutorial](https://maxdemarzi.com/2012/02/02/graph-visualization-and-neo4j-part-three/) with the requested mouseover effect.
