### ISSUE TITLE
Placeholder Subpages

### ISSUE THREAD

**Issue by julevdl** [amosproj/amos-ss2021-project2-context-map#311]
## User story
1. As a general user
2. I want / need to see what's still under construction
3. So that I can prepare for my next use

## Acceptance criteria
* For each of the following subpages create a clickable box in Dashboard and a menu tab under main menu "visualization"
* Create subpage in main menu "visualization" for: 
1. Radial Layout 
2. Betweeness Centrality 

* Under main Menu "Data" position the placeholder screenshot "list" -> no need to implement a clickable box "list" in dashboard since it's its own main menu entry 

* For each empty subpage (the above, Data) use respective screenshots the PO's prepared for you in the AMOS drive folder: https://drive.google.com/drive/folders/1lGgjpRFXst-zGH0jvxq8gmbbGLi-NE-5?usp=sharing
* For each box in Visualization Dashboard use prepared text (also found in AMOS drive folder) as a description
* on subpage that is not yet implemented add placeholder img and "coming soon"

## Definition of done
*Documentation conform with tsdoc
*Reviewed with 4 eyes principle
*Did not break other code
*Understandable documentation for developers

**Comment by derwehr** [comment]
screenshot for the schema page is missing in the drive folder

**Comment by julevdl** [comment]
> screenshot for the schema page is missing in the drive folder

trying to implement the scheme in the next sprint -> leave it  for now (updated issue)
