### ISSUE TITLE
Combination of visualization and query archetypes

### ISSUE THREAD

**Issue by julevdl** [amosproj/amos-ss2021-project2-context-map#33]
## User story
1. As a engineer & portfolio manager
2. I want / need to combine query types with suitable visualizations
3. So that my data is displayed in a meaningful way

## Acceptance criteria
* Able to select at least one visualization for each query type
* No implementation (yet) but only research, discussion and specification

## Definition of done
* Added only after week 5
* The same for all features

**BLOCKED BY #9 and #11**

**Comment by julevdl** [comment]
Issue was already completed when researching archetypes and visualization possibilities. Document to be found in teams One Drive folder.

**Comment by CatoLeanTruetschel** [comment]
The document is also accessible from [here](https://github.com/amosproj/amos-ss2021-project2-context-map/blob/main/doc/Archetypes.pdf).
