### ISSUE TITLE
Node Details

### ISSUE THREAD

**Issue by zuberman35** [amosproj/amos-ss2021-project2-context-map#342]
## User story
1. As a Business Manager
2. I want / need to understand the context of each node I see in the visualization
3. So that I can better understand the message the visualization tries to convey

## Acceptance criteria
* Applicable for all implemented visualizations (except Chord Diagram & Schema)
* When clicking on a node, open side menu next to filter
* In side menu, show available data that refers to node (descriptive data)
* pop-up when node is clicked
* Keep it stupid simple
![image](https://user-images.githubusercontent.com/65014902/123914055-44022f80-d97f-11eb-8400-11a417d1a7c0.png)

## Definition of done
* Documentation conform with tsdoc
* Reviewed with 4 eyes principle
* Did not break other code
* Understandable documentation for developers

**Comment by CatoLeanTruetschel** [comment]
Is this related to #35?
