### ISSUE TITLE
Filter enhacement

### ISSUE THREAD

**Issue by zuberman35** [amosproj/amos-ss2021-project2-context-map#345]
## User story
1. As a Business Manager
2. I want / need to see which filter is applied to my data in the current visualization
3. So that I can adjust it if needed

## Acceptance criteria
*  When applying a filter, switching visualization and returning to original visualization (a-b-a) filter options that were selected need to still be applied
*  Applies to all visualizations (except chord diagram)
![image](https://user-images.githubusercontent.com/65014902/123061120-a309f680-d40b-11eb-8ea4-d862218ce481.png)

## Definition of done
* Documentation conform with tsdoc
* Reviewed with 4 eyes principle
* Did not break other code
* Understandable documentation for developers

**Comment by CatoLeanTruetschel** [comment]
This is essentially the same as  #279
