### ISSUE TITLE
Create dockerfile and publish app automatically (CD)

### ISSUE THREAD

**Issue by CatoLeanTruetschel** [amosproj/amos-ss2021-project2-context-map#37]
Implement continous delivery (CD) by
1. Create a dockerfile
2. Build a docker image with github actions
3. Publish the images in an image repository

**Comment by CatoLeanTruetschel** [comment]
@joluj @IgorShmelev @derwehr @PianoRollRepresentation Do we actually want to implement this?

**Comment by joluj** [comment]
We need a CD or at lease CI pipeline. What are the alternatives?

I have just created the docker configuration for the database with @PianoRollRepresentation.

**Comment by PianoRollRepresentation** [comment]
I think it would be very nice since without it we would need to start frontend, backend and the DB always manually and there many resources for it, i.e. [here](https://levelup.gitconnected.com/automated-deployment-using-docker-github-actions-and-webhooks-54018fc12e32)

**Comment by CatoLeanTruetschel** [comment]
@joluj The CI setup is tracked by #20, but this can be implemented independantly via github actions, that are executed whenever a tag from the `main` branch is created.

**Comment by IgorShmelev** [comment]
I agree with @PianoRollRepresentation, this would reduce deployment complexity and human errors during e.g. sprint release.

**Comment by CatoLeanTruetschel** [comment]
Done via #337
