### ISSUE TITLE
Testfrage klären

### ISSUE THREAD

**Issue by julevdl** [amosproj/amos-ss2021-project2-context-map#4]
Dokument anfertigen, auf welcher Ebene und wie wir testen definieren
- PO Ebene 
- SD Ebene

**Comment by CatoLeanTruetschel** [comment]
I'm currently working on this together with @joluj
The current roadmap is:
* Research and collection of options and frameworks
* Create a design document proposal
* Setup a working test-environment (including github workflows - this is up for discussion)
* Present and discuss the document in the next team meeting

The living design document proposal can be found [here](https://gist.github.com/CatoLeanTruetschel/6f83135e75417fcf3ccf8b6fd8ec149e).

**Comment by CatoLeanTruetschel** [comment]
A specification proposal is created and can be found [here](https://gist.github.com/CatoLeanTruetschel/6f83135e75417fcf3ccf8b6fd8ec149e).

**Comment by joluj** [comment]
Umfrage: Upvoten für Jest. Downvoten für Cypress

**Comment by CatoLeanTruetschel** [comment]
Johannes as I fixed cypress as our test runner as of your choices and are working on the completion of the test specification document.
