### ISSUE TITLE
Find and set-up an adequate dataset

### ISSUE THREAD

**Issue by zuberman35** [amosproj/amos-ss2021-project2-context-map#5]
## User story
1. As a user
2. I want/ need access information through the database
3. So that I can get detailed insights

## Acceptance criteria
* ideally Corporate Data
* RDF/Neo4J
* checked for completeness

## Definition of done
* Added only after week 5
* The same for all features

**Comment by PianoRollRepresentation** [comment]
I wrote a document that summarizes the most important differences between RDF triplestores and neo4j to simplify which database-system we want to use in the first place: [here](https://gist.github.com/PianoRollRepresentation/be005c056ca2e85c75547176bf7f0699)

**Comment by CatoLeanTruetschel** [comment]
Moving this to the `Sprint 3` milestone, as this did not pass review today.

**Comment by joluj** [comment]
Hab beim Einlesen in neo4j ein paar Beispieldatenbanken gefunden, sind bestimmt auch für #6 interessant: https://github.com/neo4j-graph-examples

**Comment by derwehr** [comment]
Neo4j database via docker was implemented by 7ba1216ab47e95a5e40c0a27ba332c9d3c60c221
