### ISSUE TITLE
Decide on examplary dataset

### ISSUE THREAD

**Issue by zuberman35** [amosproj/amos-ss2021-project2-context-map#6]
## User story
1. As a manager
2. I want / need to present a standard example of the software 
3. So that everyone can give feedback

## Acceptance criteria
* 500 Entities (each min. 5 attributes/properties)
* 30 types 
* Randomized generated data
* Constant Data

## Definition of done
* Added only after week 5
* The same for all features

**Comment by derwehr** [comment]
Examplary dataset was added in 23b766c036e8e42f4a951c5a4c1ff29e33a323e9
But this dataset will probably be replaced with generated data for our customer's ontology in an upcoming sprint
