### ISSUE TITLE
Serve the frontend via the backend

### ISSUE THREAD

**Issue by CatoLeanTruetschel** [amosproj/amos-ss2021-project2-context-map#60]
The backend should serve the frontend, so that we can access the app simply via a webbrowser by visiting the server's HTTP-Endpoints.

**Comment by joluj** [comment]
You can use environment variables like described [in this post](https://medium.com/how-to-react/using-env-file-in-react-js-b2714235e77e). It injects the value of the environment variable at build time, this matches our use case. And it works with the app and service, i have just tested it locally.

.env:
```
REACT_APP_BACKEND_URL=http://localhost:8080/
```

.env.production:
```
REACT_APP_BACKEND_URL=https://example.com/api
```

And use it like `const url = process.env.REACT_APP_BACKEND_URL;`

**Comment by CatoLeanTruetschel** [comment]
This is needed for #76 but does not have anything to do with this issue.

**Comment by CatoLeanTruetschel** [comment]
This is no longer a requirement, as the backend API was moved to a subpath `/api` and the currentl plan is to use a reverse proxy that will serve the frontend and the backend and thus compose the projects to a unique endpoint.
