### ISSUE TITLE
Visualization of errors

### ISSUE THREAD

**Issue by CatoLeanTruetschel** [amosproj/amos-ss2021-project2-context-map#77]
Errors are currently visualized by printing the raw error message into the view, which is not very user-friendly. Additionally, the backend does not check the queries and request parameters for validity, nor are these cases handled in the front-end in an appropriate way. This could be visually marking the falsy input in red.

**Comment by CatoLeanTruetschel** [comment]
@julevdl @zuberman35 Could this be a potential user-story?

**Comment by julevdl** [comment]
Closed with #86
