### ISSUE TITLE
Handle very large graph views

### ISSUE THREAD

**Issue by CatoLeanTruetschel** [amosproj/amos-ss2021-project2-context-map#78]
Currently very large graphs cannot be displayed in a reasonable way. Currently, this looks like this the following (1000 nodes, 1500 edges)  
![grafik](https://user-images.githubusercontent.com/12112026/117631551-a52a3580-b17c-11eb-8563-46c2fdb98873.png)  

Possible ideas to solve this:  
* Filter the nodes and edges #47
* Replace subgraphs with a single substitute node, that is extracted, when clicked

**Comment by CatoLeanTruetschel** [comment]
@julevdl @zuberman35 Is this a potential user story?  
@joluj @derwehr @PianoRollRepresentation @IgorShmelev Any further ideas on how to handle this? Feel free to add it to the list above.

**Comment by julevdl** [comment]
In the future graph should only be displayed after filtering. High amount of nodes like in the above picture will not be shown. Future user stories (#47) will take care of this issue.
