### ISSUE TITLE
CI fails often due to network timeout

### ISSUE THREAD

**Issue by CatoLeanTruetschel** [amosproj/amos-ss2021-project2-context-map#79]
CI fails often due to network timeout, when yarn tries to download packages. Increase the network-timeout to solve this.

**Comment by derwehr** [comment]
dhis2/notes/issues/29 confirms this solution and https://github.com/dhis2/notes/issues/29#issuecomment-473310493 also suggests using the `--prefer-offline` flag:
>Also note that subsequent installs will likely not timeout since the large package (`material-design-icons`) will be found in yarn's cache.  As such this behavior may appear intermittent if you happen to get a cache miss when doing an install.  Using `yarn install --prefer-offline` or even `yarn install --offline` can help avoid network requests at all if you have a robust local cache (particularly useful on airplanes and in low-bandwidth situations). 
>
>Setting a long yarn timeout globally shouldn't have downsides so I use that as well.

_Originally posted by @amcgee in https://github.com/dhis2/notes/issues/29#issuecomment-473310493_
