### ISSUE TITLE
Layout of dashboard misses margins

### ISSUE THREAD

**Issue by CatoLeanTruetschel** [amosproj/amos-ss2021-project2-context-map#87]
Layout of dashboard misses margins, as margins were removed from the general layouting.

![grafik](https://user-images.githubusercontent.com/12112026/117940592-82795780-b309-11eb-9abd-a100d5f021e7.png)

**Comment by IgorShmelev** [comment]
What was the the reason to remove the margins? Without the padding/margin on the content container, the rendered pages would require additional styling.

**Comment by derwehr** [comment]
fixed in 503a91bd0f00ee8cf00d0fe150c9acd41b8dc0f3
