### ISSUE TITLE
Query-Archetypes

### ISSUE THREAD

**Issue by julevdl** [amosproj/amos-ss2021-project2-context-map#9]
## User story
1. As an engineer & portfolio manager
2. I want / need to query data in various ways
3. So that the software can be used for every part of the company
## Acceptance criteria
* No implementation (yet) but research, discussion and specification
* Overview over different query types
* Works for neo4j and RDF

## Definition of done
* Added only after week 5
* The same for all features

**Comment by joluj** [comment]
Created a [document](https://github.com/amosproj/amos-ss2021-project2-context-map/blob/main/doc/Archetypes.pdf) with the archetypes and corresponding visualization ideas (with @CatoLeanTruetschel and @IgorShmelev).

Closes #9. Closes #11.

**Comment by CatoLeanTruetschel** [comment]
Implemented by 98fe3bd6b172bb95a94059f70b55fb30c5d12589
