### ISSUE TITLE
Make frontend-backend communication generic

### ISSUE THREAD

**Issue by joluj** [amosproj/amos-ss2021-project2-context-map#90]
ATM the HTTP-communication is handled completely in QueryServiceImpl.ts.
We need a generic solution (-> `HttpService`) for the network communication so common details like base-url, headers are handled only once.

Example calls of that:
```ts
// returns Promise<MyReturnType> and calls GET http://example.com/api/getNodeDetails
httpService.get<MyReturnType>('getNodeDetails'); 

// return Promise<MyReturnType> and calls POST http://example.com/api/queryAll with Body myBody
httpService.post<MyReturnType>('queryAll', { body: myBody });

// sets header 'MyHeader' to 'myValue'
httpService.post<MyReturnType>('queryAll', { body: myBody, headers: {'MyHeader': 'myValue' }});
```

**Comment by CatoLeanTruetschel** [comment]
The API proposal looks good to me. We need a method for GET request with query parameters, too. It is possible that it's the callers responsibility to encode this in the request URL, but I would prefer a method that handles this for the caller.
```
// returns Promise<MyReturnType> and calls 
// GET http://example.com/api/getNodeDetails?ids=1&ids=2&ids=3&ids=4&otherProp=abc
httpService.get<MyReturnType>('getNodeDetails', { ids: [1, 2, 3, 4], otherProp: 'abc' }); 
```
