### ISSUE TITLE
Show entity types in graph visualization

### ISSUE THREAD

**Issue by CatoLeanTruetschel** [amosproj/amos-ss2021-project2-context-map#99]
Show visually the types, nodes and edges belongs to, for example with different colors, stroke styles, etc.   
A problem here is that nodes may belong to multiple node types.
This is blocked by #98

**Comment by CatoLeanTruetschel** [comment]
/CC @julevdl @zuberman35 This is a possible user-story.

**Comment by julevdl** [comment]
Covered by issue #199
